version: '0.1'
services:
  message-server:
    image: message-server
    container_name: message-server
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      CHAT_IDS: ${CHAT_IDS}
      PORT: ${PORT}
    ports:
      - "${HOST_PORT}:${PORT}"
    networks:
      - message-server
    command: npm start
networks:
  message-server: